/* eslint-disable @next/next/no-page-custom-font */
/* eslint-disable @next/next/google-font-display */
import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import './_scss/global.scss';
import './_scss/basic.scss';
import { Navbar } from '@/_components/Navbar';
import { Footer } from '@/_components/Footer';
import { THEME, ThemeProvider } from '@/_context/themeContext';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { QueryProvider } from '@/_context/queryContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  // need to use next/headers because layout.tsx execute at server side, js-cookies is execute at client side
  const cookieStore = await cookies();
  const theme = cookieStore.get('theme')?.value as THEME;
  const message = await getMessages();
  return (
    <html lang={locale} className="bg-pure-white dark:bg-pure-black">
      <NextIntlClientProvider messages={message}>
        <head>
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0&icon_names=clear_day"
          />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased w-full`}
        >
          <QueryProvider>
            <ThemeProvider value={theme || 'light'}>
              <div className="w-full min-h-screen bg-base-light dark:bg-base-dark">
                <Navbar />
                <div>{children}</div>
                <Footer />
              </div>
            </ThemeProvider>
          </QueryProvider>
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
